--- # Include task example
- hosts: apache-client
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify telnet packages are installed
      raw: yum list installed | grep telnet > /home/test/telnet.log
    - name: Verify lynx packages are installed
      raw: yum list installed | grep lynx > /home/test/lynx.log
