--- #My first YAML playbook for Ansible
- hosts: all 
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_ver: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
    - name: pkg_name
#      prompt: Install Which Package    ##prompts for a package name
#      prompt: web_domain    ##prompts for domain name
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async: 300      #will help forking proccess in large environments
      poll: 3
      notify: Restart HTTPD
    - name: Install Lynx
      action: yum name={{ pkg_name }} state=installed
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted

