--- # prompt for user package example
- hosts: apache-client
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
      playbook_version: 0.01.b
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install Which Package?
      default: telnet
      private: no
  tasks:
    - name: Install the package
      yum: pkg={{ pkgtoinstall }} state=latest      
