--- # outline to playbook translation
- hosts: all
  user: test
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time stamp for when playbook starts
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: install httpd
    yum: pkg=httpd state=latest
    notify: Start HTTPD
  - name: verify httpd is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install telnet
    yum: pkg=telnet state=latest
  - name: install lynx
    yum: pkg=lynx state=latest     
  - name: log all packages installed
    command: yum list installed
    register: installed_result
  - debug: var=installed_result
  - name: date/time stamp for when playbook ends
    command: /usr/bin/date
    register: timestamp_end
  - debug: var=timestamp_end
  handlers:
  - name: Start HTTPD
    service: name=httpd state=restarted
